### ISSUE TITLE
Problem with locale.

### ISSUE THREAD

**Issue by SANCTISGROUP** [imkuroneko/neko_alertas_defcon#1]
Hi ! Very nice but small problem with the localities and languages, the menu is displayed in the call format.
![problem](https://github.com/imkuroneko/neko_alertas_defcon/assets/135251316/22615834-96a3-402a-8574-a5498a547179)

**Comment by imkuroneko** [comment]
Hi @HumiPen!

Please check the [v1.1.0b release](https://github.com/imkuroneko/neko_alertas_defcon/releases/tag/v1.1.0b)

I added the `en.json` file for english (please update it as you want and need... I did it on a basic way with Google Translate because english is not my main language ^^,)
