### ISSUE TITLE
Defcon management

### ISSUE THREAD

**Issue by SANCTISGROUP** [imkuroneko/neko_alertas_defcon#2]
Good morning !
I would like to know if it was possible to remove the automatic management of the defcon (the fact that it resets to 0 on each reboot in particular) and that it keeps the same value which was indicated?

**Comment by imkuroneko** [comment]
Hi hi!
That's related because `0` it's the default value; so on every script/server restart will rollback on that value...

I'm still working on a way for store that value and will release an update soon :unicorn:

**Comment by imkuroneko** [comment]
Hi @HumiPen You can get on the [latest release](https://github.com/imkuroneko/neko_alertas_defcon/releases/tag/v1.1.2) the update for persistence data storage (on a JSON file on the current path)
