### ISSUE TITLE
Problem with menu.

### ISSUE THREAD

**Issue by SANCTISGROUP** [imkuroneko/neko_alertas_defcon#3]
I'm bothering you again!
Since the update, the menu is no longer displayed (no error neither console nor f8).

**Comment by imkuroneko** [comment]
Hi hi @HumiPen  I released a new version `v1.1.3` now it will check if `job.type == leo`; beside that, can you tell me if it show the command on the chat (the autocomplete) or not? maybe you modified before and was reseted on the update (also if you can upload a video trying it will help too pls)

**Comment by SANCTISGROUP** [comment]
It's ok on the menu side, however this time it doesn't update the logo on my side.

**Comment by imkuroneko** [comment]
can you add `print("currentStatus : ".. data.status)` here? Let's check if you get the current status on your client side

![image](https://github.com/imkuroneko/neko_alertas_defcon/assets/20273059/176c35ff-f952-438f-bc71-3605f39514b4)

**Comment by imkuroneko** [comment]
@HumiPen hi hii~ can you try this new release? I think now this should fix your issue ^^,

https://github.com/imkuroneko/neko_alertas_defcon/releases/tag/v1.1.4
